version: "3.9"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "500k"
    max-file: "20"

services:
  crypto-miner:
    container_name: crypto-miner
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    logging: *default-logging
    networks:
      - crypto-miner
    environment:     
      - MINING_POOL=stratum+tcp://randomxmonero.auto.nicehash.com:9200
      - MINING_COIN=XMR
      - WALLET_ADDRESS=86A7wUCQ6V81YgJc5g1k8118BdEEdKbso4Eg9kd4RBXfj8jCosqsp6QBbZquSjbrHJYyvxUoF19fcKhipD4Z3xWPKjnLURp
      - WORKER_NAME=NHbQPGPMeAgGaLV9CUQ7bQaJQ2VJv96AUMbB

networks:
  crypto-miner:
