---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xmrig-miner
  labels:
    app: xmrig-miner
spec:
  selector:
    matchLabels:
      app: xmrig-miner
  template:
    metadata:
      labels:
        app: xmrig-miner
    spec:
      containers:
      - name: xmrig-miner
        image: ghcr.io/ci-monk/docker-xmrig-miner:main
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: "America/Sao_Paulo"
        - name: MINING_POOL
          value: "rx.unmineable.com:3333"
        - name: MINING_COIN
          value: "SHIB"
        - name: REFERRAL_CODE
          value: "7lkr-kmhq"
        - name: WALLET_ADDRESS
          value: "0xE36B97Ec98dD179B89BC109c11Eb47D6B587f3F3"
        - name: WORKER_NAME
          value: "kubernetes"
        resources:
          limits:
            cpu: "2000m"
            memory: "8Gi"
          requests:
            cpu: "1000m"
            memory: "4Gi"
