apiVersion: v2
name: xmrig
description: A Helm chart for XMRig Monero Miner
type: application
version: 0.1.0
appVersion: "1.16.0"
icon: https://xmrig.com/assets/img/xmrig-logo.svg
home: https://xmrig.com
sources:
  - https://github.com/xmrig/xmrig
maintainers:
  - name: Lucca
    email: lpsm-dev@protonmail.com
